---
- name: Panorama Template
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:

    - name: include variables
      include_vars: ~/ansible/group_vars/panos/vars.yml
      no_log: 'yes'


    - name: Panorama Template 
      element: |-
        <entry name="Test_Template">
          <settings>
            <default-vsys>vsys1</default-vsys>
          </settings>
          <config>
            <devices>
              <entry name="localhost.localdomain">
                <vsys>
                  <entry name="vsys1"/>
                </vsys>
              </entry>
            </devices>
          </config>
        </entry>
    cmd: set        

 
